swagger: "2.0"
info:
  version: "1.0.0"
  title: "API Hotel"
tags:
- name: "booking"
  description: "Making bookings"
- name: "checkIn"
  description: "Settlement"
- name: "checkOut"
  description: "Eviction"
- name: "statistic"
  description: "Statistic"
paths:
  /booking/:
    get:
      tags:
      - "booking"
      operationId: "getBooking"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: '#/definitions/Reception'
    put:
      tags:
      - "booking"
      description: "put book"
      operationId: "putBooking"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Booking"
      responses:
        200:
          description: "successful operation"
  /booking/{idBooking}:
    put:
      tags:
      - "booking"
      description: "update book"
      operationId: "updateBooking"
      produces:
      - "application/json"
      parameters:
      - name: "idBooking"
        in: "path"
        description: "book id"
        required: true
        type: "integer"
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Booking"
      responses:
        200:
          description: "successful operation"
    delete:
      tags:
      - "booking"
      description: "delete book"
      operationId: "deleteBooking"
      produces:
      - "application/json"
      parameters:
      - name: "idBooking"
        in: "path"
        description: "book id"
        required: true
        type: "integer"
      responses:
        200:
          description: "successful operation"
  /checkIn/:
    get:
      tags:
      - "checkIn"
      operationId: "getCheckIn"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: '#/definitions/Reception'
    put:
      tags:
      - "checkIn"
      description: "put checkIn"
      operationId: "putCheckIn"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Booking"
      responses:
        200:
          description: "successful operation"
  /checkIn/{idCheckIn}:
    put:
      tags:
      - "checkIn"
      description: "update checkIn"
      operationId: "updateCheckIn"
      produces:
      - "application/json"
      parameters:
      - name: "idCheckIn"
        in: "path"
        description: "checkIn id"
        required: true
        type: "integer"
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Booking"
      responses:
        200:
          description: "successful operation"
  /checkOut/:
    get:
      tags:
      - "checkOut"
      description: "put checkOut"
      operationId: "putCheckOut"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/CheckOut"
      responses:
        200:
          description: "successful operation"
  /statistic/getRooms?dateFrom={dateFrom}&dateTo={dateTo}&type={type}}:
    get:
      tags:
      - "statistic"
      description: "statistic"
      operationId: "statistic"
      produces:
      - "application/json"
      parameters:
      - name: "dateFrom"
        in: "path"
        description: "start period"
        required: true
        type: "string"
      - name: "dateTo"
        in: "path"
        description: "end period"
        required: true
        type: "string"
      - name: "type"
        in: "path"
        description: "type"
        required: true
        type: "string"
        enum:
          - FREE
          - BOOKED
          - CHECKED_IN
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: '#/definitions/Reception'
definitions:
  Reception:
    properties:
      id:
        type: "integer"
      to:
        type: "string"
      from:
        type: "string"
      guest:
        properties:
          id:
            type: "integer"
          address:
            type: "string"
          country:
            properties:
              id:
                type: "integer"
              name:
                type: "string"
          firstName:
            type: "string"
          middleName:
            type: "string"
          secondName:
            type: "string"
          phone:
            type: "string"
      room:
        properties:
          id:
            type: "integer"
          price_per_night:
            type: "number"
          floor:
            type: "integer"
          room_type_id:
            properties:
              id:
                type: "integer"
              name:
                type: "string"
      roomStatus:
        properties:
          id:
            type: "integer"
          name:
            type: "string"

  Booking:
    properties:
      from:
        type: "string"
      to:
        type: "string"
      guest:
        type: "integer"
      room:
       type: "integer"
  CheckOut:
    properties:
      id:
        type: "integer"
      to:
        type: "string"